import { supabase } from "./supabase";

function requireClient() { if (!supabase) throw new Error("Supabase is not configured."); return supabase; }
export async function currentUserId() { const { data, error } = await requireClient().auth.getUser(); if (error) throw error; return data.user?.id || null; }
export async function listTrips() { const client = requireClient(); const userId = await currentUserId(); if (!userId) return []; const { data, error } = await client.from("trips").select("id,name,start_date,end_date,description,cover_photo_url,budget,is_public,created_at,trip_stops(count)").eq("user_id", userId).order("created_at", { ascending: false }); if (error) throw error; return data || []; }
export async function createTrip(input: { name: string; start_date?: string; end_date?: string; description?: string; budget?: number }) { const client = requireClient(); const userId = await currentUserId(); if (!userId) throw new Error("Please sign in first."); const { data, error } = await client.from("trips").insert({ ...input, user_id: userId }).select().single(); if (error) throw error; return data; }
export async function updateTrip(id: string, input: Record<string, unknown>) { const { data, error } = await requireClient().from("trips").update(input).eq("id", id).select().single(); if (error) throw error; return data; }
export async function deleteTrip(id: string) { const { error } = await requireClient().from("trips").delete().eq("id", id); if (error) throw error; }
export async function listStops(tripId: string) { const { data, error } = await requireClient().from("trip_stops").select("*,activities(*)").eq("trip_id", tripId).order("order_index"); if (error) throw error; return data || []; }
export async function addStop(input: { trip_id: string; city_name: string; country?: string; lat?: number; lon?: number; start_date?: string; end_date?: string; order_index: number }) { const { data, error } = await requireClient().from("trip_stops").insert(input).select().single(); if (error) throw error; return data; }
export async function addActivity(input: { trip_stop_id: string; name: string; category?: string; cost?: number; day_number?: number; time?: string; image_url?: string; description?: string }) { const { data, error } = await requireClient().from("activities").insert(input).select().single(); if (error) throw error; return data; }
export async function deleteActivity(id: string) { const { error } = await requireClient().from("activities").delete().eq("id", id); if (error) throw error; }
export async function listCommunityPosts() { const { data, error } = await requireClient().from("community_posts").select("id,content,created_at,user_id,trip_id").order("created_at", { ascending: false }); if (error) throw error; return data || []; }
export async function createCommunityPost(content: string, tripId?: string) { const userId = await currentUserId(); if (!userId) throw new Error("Please sign in first."); const { data, error } = await requireClient().from("community_posts").insert({ user_id: userId, content, trip_id: tripId || null }).select().single(); if (error) throw error; return data; }
export async function uploadTripCover(file: File, tripId: string) { const userId = await currentUserId(); if (!userId) throw new Error("Please sign in first."); const path = `${userId}/${tripId}-${crypto.randomUUID()}.${file.name.split(".").pop() || "jpg"}`; const { error } = await requireClient().storage.from("trip-covers").upload(path, file, { upsert: false, contentType: file.type }); if (error) throw error; const { data } = requireClient().storage.from("trip-covers").getPublicUrl(path); return data.publicUrl; }
export async function uploadAvatar(file: File) { const userId = await currentUserId(); if (!userId) throw new Error("Please sign in first."); const path = `${userId}/${crypto.randomUUID()}.${file.name.split(".").pop() || "jpg"}`; const { error } = await requireClient().storage.from("avatars").upload(path, file, { upsert: false, contentType: file.type }); if (error) throw error; const { data } = requireClient().storage.from("avatars").getPublicUrl(path); return data.publicUrl; }
export async function deleteAccountData() { const client = requireClient(); const userId = await currentUserId(); if (!userId) throw new Error("Please sign in first."); const { error: tripError } = await client.from("trips").delete().eq("user_id", userId); if (tripError) throw tripError; const { error: profileError } = await client.from("profiles").delete().eq("id", userId); if (profileError) throw profileError; const { error: signOutError } = await client.auth.signOut(); if (signOutError) throw signOutError; }
export async function copySharedTrip(tripId: string) { const client = requireClient(); const userId = await currentUserId(); if (!userId) throw new Error("Please sign in first."); const { data: rows, error: readError } = await client.from("public_shared_itineraries").select("trip_id,name,start_date,end_date,description,cover_photo_url,city_name,country,stop_start_date,stop_end_date,order_index,activity_name,category,cost,time,image_url,activity_description").eq("trip_id", tripId).order("order_index"); if (readError) throw readError; if (!rows?.length) throw new Error("This shared itinerary is no longer available."); const first = rows[0]; const { data: trip, error: tripError } = await client.from("trips").insert({ user_id: userId, name: `${first.name || "Shared itinerary"} (copy)`, start_date: first.start_date, end_date: first.end_date, description: first.description, cover_photo_url: first.cover_photo_url, is_public: false }).select().single(); if (tripError) throw tripError; const grouped = new Map<string, any>(); for (const row of rows) { const key = `${row.city_name}-${row.order_index}`; if (!grouped.has(key)) grouped.set(key, { trip_id: trip.id, city_name: row.city_name, country: row.country, start_date: row.stop_start_date, end_date: row.stop_end_date, order_index: row.order_index, activities: [] }); if (row.activity_name) grouped.get(key).activities.push(row); } for (const stop of Array.from(grouped.values())) { const { data: createdStop, error: stopError } = await client.from("trip_stops").insert({ trip_id: trip.id, city_name: stop.city_name, country: stop.country, start_date: stop.start_date, end_date: stop.end_date, order_index: stop.order_index }).select().single(); if (stopError) throw stopError; if (stop.activities.length) { const { error: activitiesError } = await client.from("activities").insert(stop.activities.map((a: any) => ({ trip_stop_id: createdStop.id, name: a.activity_name, category: a.category, cost: a.cost || 0, time: a.time, image_url: a.image_url, description: a.activity_description }))); if (activitiesError) throw activitiesError; } } return trip; }
