import { useEffect, useMemo, useState } from "react";
import { Link } from "wouter";
import {
  ArrowRight, BarChart3, Bell, CalendarDays, ChevronDown, ChevronLeft, ChevronRight,
  Compass, Copy, DollarSign, Grid2X2, Heart, ImagePlus, LayoutDashboard, ListTodo,
  LogOut, MapPin, Menu, MoreHorizontal, Plus, Search, Settings, Share2, Sparkles,
  Trash2, TrendingUp, Users, X, Plane, Clock3, CheckCircle2
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";
import { supabase } from "@/lib/supabase";
import { trpc } from "@/lib/trpc";
import { addStop, createCommunityPost, createTrip, currentUserId, deleteAccountData, deleteTrip, listCommunityPosts, uploadAvatar, uploadTripCover, updateTrip } from "@/lib/globetrotterData";

const destinations = [
  { city: "Lisbon", country: "Portugal", image: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?auto=format&fit=crop&w=900&q=80", tag: "Culture & food" },
  { city: "Kyoto", country: "Japan", image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=900&q=80", tag: "Slow travel" },
  { city: "Reykjavik", country: "Iceland", image: "https://images.unsplash.com/photo-1504829857797-ddff29c27927?auto=format&fit=crop&w=900&q=80", tag: "Wild escapes" },
];

const initialTrips = [
  { id: 1, name: "Japan Adventure", dates: "Apr 12 – Apr 22, 2025", stops: 3, status: "Upcoming", image: destinations[1].image, color: "teal" },
  { id: 2, name: "Coastal Portugal", dates: "Jun 08 – Jun 15, 2025", stops: 2, status: "Planning", image: destinations[0].image, color: "blue" },
  { id: 3, name: "Nordic Summer", dates: "Aug 19 – Aug 29, 2025", stops: 4, status: "Planning", image: destinations[2].image, color: "gold" },
];

const nav = [
  { label: "Overview", icon: LayoutDashboard, key: "overview" },
  { label: "My trips", icon: Plane, key: "trips" },
  { label: "Explore", icon: Compass, key: "explore" },
  { label: "Itinerary", icon: ListTodo, key: "itinerary" },
  { label: "Calendar", icon: CalendarDays, key: "calendar" },
  { label: "Community", icon: Users, key: "community" },
];

function Stat({ icon: Icon, label, value, helper, accent }: any) {
  return <div className="stat-card"><div className={`stat-icon ${accent}`}><Icon size={18} /></div><div><p className="eyebrow">{label}</p><p className="stat-value">{value}</p><p className="stat-helper">{helper}</p></div></div>;
}

function TripCard({ trip, onDelete, onOpen }: any) {
  return <article className="trip-card"><div className="trip-image" style={{ backgroundImage: `linear-gradient(180deg, transparent 36%, rgba(7,18,27,.78)), url(${trip.image})` }}><Badge className={`trip-status ${trip.status === "Upcoming" ? "upcoming" : "planning"}`}>{trip.status}</Badge><button className="icon-button over-image"><MoreHorizontal size={18} /></button><div className="trip-image-caption"><p>{trip.name}</p><span>{trip.dates}</span></div></div><div className="trip-card-body"><div className="trip-meta"><span><MapPin size={14} /> {trip.stops} destinations</span><span><Clock3 size={14} /> 8 days</span></div><div className="trip-card-actions"><Button variant="outline" size="sm" onClick={() => onOpen(trip)}>View itinerary</Button><button className="text-button danger" onClick={() => onDelete(trip.id)}><Trash2 size={14} /> Delete</button></div></div></article>;
}

function Sidebar({ active, setActive, mobileOpen, setMobileOpen }: any) {
  return <aside className={`sidebar ${mobileOpen ? "open" : ""}`}><div className="brand"><span className="brand-mark"><Compass size={21} /></span><span>globe<span>trotter</span></span><button className="mobile-close" onClick={() => setMobileOpen(false)}><X size={20} /></button></div><div className="sidebar-section"><p className="sidebar-label">Workspace</p>{nav.map(item => <button key={item.key} className={`nav-item ${active === item.key ? "active" : ""}`} onClick={() => { setActive(item.key); setMobileOpen(false); }}><item.icon size={18} /><span>{item.label}</span>{item.key === "community" && <span className="nav-dot" />}</button>)}</div><div className="sidebar-section sidebar-bottom"><p className="sidebar-label">Manage</p><button className={`nav-item ${active === "analytics" ? "active" : ""}`} onClick={() => setActive("analytics")}><BarChart3 size={18} /><span>Analytics</span></button><button className={`nav-item ${active === "settings" ? "active" : ""}`} onClick={() => setActive("settings")}><Settings size={18} /><span>Settings</span></button><div className="upgrade-card"><Sparkles size={17} /><p><b>Make every trip count.</b><br/><span>Unlock smart planning tools.</span></p><ArrowRight size={16} /></div><div className="profile-mini"><div className="avatar">AM</div><div><b>Alex Morgan</b><span>Traveler profile</span></div><MoreHorizontal size={17} /></div></div></aside>;
}

function Topbar({ setMobileOpen, active }: any) {
  const title = nav.find(n => n.key === active)?.label || ({ analytics: "Analytics", settings: "Settings" } as any)[active] || "Overview";
  return <header className="topbar"><button className="mobile-menu" onClick={() => setMobileOpen(true)}><Menu size={22} /></button><div><p className="breadcrumb">Workspace <ChevronRight size={13} /> <b>{title}</b></p><h1>{title}</h1></div><div className="top-actions"><button className="icon-button"><Search size={19} /></button><button className="icon-button notification"><Bell size={19} /><i /></button><div className="top-avatar">AM</div></div></header>;
}

function Overview({ setActive, trips, setTrips }: any) {
  const [showForm, setShowForm] = useState(false); const [name, setName] = useState(""); const [destination, setDestination] = useState(""); const [coverFile, setCoverFile] = useState<File>();
  const addTrip = async () => { if (!name.trim()) return toast.error("Give your trip a name first."); try { if (supabase) { const created = await createTrip({ name, description: destination ? `Starting in ${destination}` : undefined }); let image = destinations[0].image; if (coverFile && supabase) { image = await uploadTripCover(coverFile, created.id); await updateTrip(created.id, { cover_photo_url: image }); } if (destination && supabase) await addStop({ trip_id: created.id, city_name: destination, order_index: 0 }); setTrips([{ id: created.id, name: created.name, dates: "Dates to be planned", stops: destination ? 1 : 0, status: "Planning", image, color: "blue" }, ...trips]); } else setTrips([{ id: Date.now(), name, dates: "Dates to be planned", stops: 0, status: "Planning", image: destinations[0].image, color: "blue" }, ...trips]); setName(""); setDestination(""); setCoverFile(undefined); setShowForm(false); toast.success("Trip created. Let’s add your first destination."); setActive("trips"); } catch (error: any) { toast.error(error.message || "Could not create trip."); } };
  return <><section className="hero"><div><p className="eyebrow accent-text">Tuesday, March 18, 2025</p><h2>Good morning, Alex <span>✦</span></h2><p className="hero-copy">Your next great adventure is closer than you think.</p></div><Button className="primary-button" onClick={() => setShowForm(true)}><Plus size={18} /> Plan a new trip</Button></section>{showForm && <div className="inline-form"><div><p className="eyebrow">New trip</p><h3>Where are you headed?</h3></div><Input autoFocus placeholder="e.g. Summer in Italy" value={name} onChange={e => setName(e.target.value)} onKeyDown={e => e.key === "Enter" && addTrip()} /><Input placeholder="First destination, e.g. Rome" value={destination} onChange={e => setDestination(e.target.value)} /><label className="upload-button">Add cover<input type="file" accept="image/*" onChange={e => setCoverFile(e.target.files?.[0])}/></label><Button className="primary-button" onClick={addTrip}>Create trip</Button><button className="icon-button" onClick={() => setShowForm(false)}><X size={18}/></button></div>}<div className="stats-grid"><Stat icon={Plane} label="Upcoming trips" value="03" helper="2 in the next 90 days" accent="teal"/><Stat icon={MapPin} label="Places visited" value="18" helper="Across 9 countries" accent="blue"/><Stat icon={DollarSign} label="Trip budget used" value="$1,240" helper="48% of your total" accent="gold"/><Stat icon={TrendingUp} label="Travel streak" value="12 mo" helper="Keep exploring" accent="pink"/></div><div className="section-heading"><div><p className="eyebrow">Your travel plans</p><h3>Upcoming trips</h3></div><button className="link-button" onClick={() => setActive("trips")}>View all <ArrowRight size={15}/></button></div><div className="trip-grid">{trips.slice(0, 3).map((trip: any) => <TripCard key={trip.id} trip={trip} onDelete={(id: number) => setTrips(trips.filter((t: any) => t.id !== id))} onOpen={() => setActive("trips")} />)}<button className="add-trip-card" onClick={() => setShowForm(true)}><span><Plus size={20}/></span><b>Plan another adventure</b><small>Start with a destination</small></button></div><div className="section-heading explore-heading"><div><p className="eyebrow">Curated for you</p><h3>Find your next place</h3></div><button className="link-button" onClick={() => setActive("explore")}>Explore destinations <ArrowRight size={15}/></button></div><div className="destination-grid">{destinations.map(d => <button className="destination-card" key={d.city} onClick={() => { setActive("explore"); toast.success(`${d.city} added to your explore list.`); }} style={{ backgroundImage: `linear-gradient(180deg, transparent 20%, rgba(7,18,27,.84)), url(${d.image})` }}><span className="destination-tag">{d.tag}</span><div><b>{d.city}</b><small>{d.country}</small></div></button>)}</div></>;
}

function Trips({ trips, setTrips, setActive }: any) { return <><div className="page-intro"><div><p className="eyebrow accent-text">Your collection</p><h2>All trips</h2><p>Keep every route, reservation, and memory in one place.</p></div><Button className="primary-button" onClick={() => setActive("overview")}><Plus size={18}/> Plan a new trip</Button></div><div className="filter-row"><div className="search-field"><Search size={16}/><input placeholder="Search trips" /></div><button className="filter-button">All trips <ChevronDown size={15}/></button><button className="filter-button">Sort by <ChevronDown size={15}/></button></div><div className="trip-list">{trips.map((trip: any) => <TripCard key={trip.id} trip={trip} onDelete={async (id: string | number) => { try { if (supabase && typeof id === "string") await deleteTrip(id); setTrips(trips.filter((t: any) => t.id !== id)); toast.success("Trip deleted"); } catch (error: any) { toast.error(error.message || "Could not delete trip."); } }} onOpen={() => toast.info("Itinerary view is ready for this trip.")} />)}</div></> }

function Explore({ setActive }: any) { const [query, setQuery] = useState(""); return <><div className="page-intro"><div><p className="eyebrow accent-text">Wander further</p><h2>Explore destinations</h2><p>Search cities and discover places worth building a trip around.</p></div></div><div className="explore-search"><Search size={18}/><input placeholder="Search city, country, or experience" value={query} onChange={e => setQuery(e.target.value)} /><Button className="primary-button">Search</Button></div><div className="destination-large-grid">{destinations.filter(d => !query || `${d.city} ${d.country}`.toLowerCase().includes(query.toLowerCase())).map(d => <article className="explore-card" key={d.city}><img src={d.image}/><div className="explore-card-body"><div><p className="eyebrow">{d.tag}</p><h3>{d.city}</h3><span>{d.country}</span></div><button className="heart-button"><Heart size={17}/></button><Button variant="outline" onClick={() => { toast.success(`${d.city} is ready to add to a trip.`); setActive("trips"); }}>Add to trip <Plus size={15}/></Button></div></article>)}</div></> }

function CalendarPage() { return <><div className="page-intro"><div><p className="eyebrow accent-text">Your timeline</p><h2>March 2025</h2><p>See your travel plans at a glance.</p></div><div className="calendar-controls"><button className="icon-button"><ChevronLeft size={17}/></button><button className="icon-button"><ChevronRight size={17}/></button></div></div><div className="calendar-shell"><div className="calendar-head">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(x => <b key={x}>{x}</b>)}</div><div className="calendar-grid">{Array.from({length: 35}, (_, i) => <div className={`calendar-day ${i === 17 ? "today" : ""}`} key={i}><span>{i < 2 ? "" : (i - 1)}</span>{i === 13 && <em className="calendar-event teal-event">Japan Adventure</em>}{i === 20 && <em className="calendar-event blue-event">Coastal Portugal</em>}{i === 27 && <em className="calendar-event gold-event">Nordic Summer</em>}</div>)}</div></div></> }

function Community() { const [posts, setPosts] = useState(["Share your favorite hidden gems with the community.", "What’s the one place you would visit again in a heartbeat?"]); const [text, setText] = useState(""); return <><div className="page-intro"><div><p className="eyebrow accent-text">Travel together</p><h2>Community</h2><p>Get inspired by people who never stop exploring.</p></div></div><div className="community-layout"><div className="post-composer"><div className="avatar">AM</div><div><Textarea placeholder="Share a travel thought, tip, or story..." value={text} onChange={e => setText(e.target.value)} /><div className="composer-actions"><button><ImagePlus size={16}/> Add photo</button><Button className="primary-button" onClick={() => { if (text.trim()) { setPosts([text, ...posts]); setText(""); toast.success("Post shared with the community."); } }}>Share post</Button></div></div></div><div className="post-list">{posts.map((p, i) => <article className="community-post" key={i}><div className="post-author"><div className="avatar small">{i ? "SK" : "AM"}</div><div><b>{i ? "Sam Kim" : "Alex Morgan"}</b><span>{i ? "2 hours ago · Kyoto" : "Just now · Traveler notes"}</span></div><MoreHorizontal size={17}/></div><p>{p}</p><div className="post-actions"><button><Heart size={16}/> 12</button><button><Share2 size={16}/> Share</button></div></article>)}</div></div></> }

function Analytics() { const [summary, setSummary] = useState({ trips: 24, users: 8, cities: 42 }); useEffect(() => { const client = supabase; if (!client) return; client.from("admin_trip_counts").select("trip_count,user_count").maybeSingle().then(({ data }) => { if (data) setSummary({ trips: Number(data.trip_count || 0), users: Number(data.user_count || 0), cities: summary.cities }); }); }, []); return <><div className="page-intro"><div><p className="eyebrow accent-text">Your patterns</p><h2>Travel analytics</h2><p>A simple view of how you spend your time exploring.</p></div></div><div className="stats-grid"><Stat icon={Plane} label="Trips tracked" value={String(summary.trips).padStart(2, "0")} helper="Protected aggregate" accent="teal"/><Stat icon={MapPin} label="Active travelers" value={String(summary.users).padStart(2, "0")} helper="Across the workspace" accent="blue"/><Stat icon={DollarSign} label="Average trip cost" value="$1,680" helper="Down 6% vs last year" accent="gold"/></div><div className="analytics-grid"><div className="panel chart-panel"><div className="panel-heading"><div><p className="eyebrow">Trip activity</p><h3>Exploration over time</h3></div><Badge>Last 12 months</Badge></div><div className="bar-chart">{[42,58,48,72,65,83,55,90,68,78,92,76].map((h,i)=><div className="bar-col" key={i}><span style={{height:`${h}%`}}></span><small>{["Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec","Jan","Feb","Mar"][i]}</small></div>)}</div></div><div className="panel breakdown"><div className="panel-heading"><div><p className="eyebrow">Budget split</p><h3>Where it goes</h3></div></div><div className="donut"><div><b>48%</b><small>used</small></div></div><div className="legend"><span><i className="dot teal-dot"/>Stay <b>42%</b></span><span><i className="dot blue-dot"/>Activities <b>31%</b></span><span><i className="dot gold-dot"/>Meals <b>27%</b></span></div></div></div><AdminInsights/></> }

function AdminInsights() { const [cities, setCities] = useState<any[]>([]); const [activities, setActivities] = useState<any[]>([]); useEffect(() => { if (!supabase) return; Promise.all([supabase.from("admin_popular_cities").select("city_name,stop_count").limit(5), supabase.from("admin_popular_activities").select("name,activity_count").limit(5)]).then(([cityResult, activityResult]) => { setCities(cityResult.data || []); setActivities(activityResult.data || []); }); }, []); return <div className="insights-grid"><div className="panel"><p className="eyebrow">Popular cities</p>{cities.length ? cities.map(item => <div className="insight-row" key={item.city_name}><span>{item.city_name}</span><b>{item.stop_count}</b></div>) : <p className="muted-copy">No city data yet.</p>}</div><div className="panel"><p className="eyebrow">Popular activities</p>{activities.length ? activities.map(item => <div className="insight-row" key={item.name}><span>{item.name}</span><b>{item.activity_count}</b></div>) : <p className="muted-copy">No activity data yet.</p>}</div></div> }

export default function Home({ initialActive = "overview" }: { initialActive?: string }) { const [active, setActive] = useState(initialActive); const [mobileOpen, setMobileOpen] = useState(false); const [trips, setTrips] = useState(initialTrips); const [selectedTrip, setSelectedTrip] = useState<any>(null); useEffect(() => { let mounted = true; const client = supabase; if (!client) return; client.auth.getUser().then(async ({ data }) => { if (!data.user) return; const { data: rows } = await client.from("trips").select("id,name,start_date,end_date,cover_photo_url").eq("user_id", data.user.id).order("created_at", { ascending: false }); if (mounted && rows?.length) setTrips(rows.map((row: any) => ({ id: row.id, name: row.name, dates: row.start_date && row.end_date ? `${row.start_date} – ${row.end_date}` : "Dates to be planned", stops: 0, status: "Planning", image: row.cover_photo_url || destinations[0].image, color: "blue" }))); }); return () => { mounted = false; }; }, []); const content = useMemo(() => ({ overview: <Overview setActive={setActive} trips={trips} setTrips={setTrips}/>, trips: <Trips trips={trips} setTrips={setTrips} setActive={setActive}/>, explore: <ExploreLive setActive={setActive} trips={trips} setTrips={setTrips}/>, itinerary: <ItineraryPage/>, calendar: <CalendarPage/>, community: <CommunityLive/>, analytics: <Analytics/>, settings: <SettingsPage/> } as any)[active], [active, trips]); return <div className="app-shell"><Sidebar active={active} setActive={setActive} mobileOpen={mobileOpen} setMobileOpen={setMobileOpen}/>{mobileOpen && <div className="sidebar-scrim" onClick={() => setMobileOpen(false)}/>}<main className="main-content"><Topbar setMobileOpen={setMobileOpen} active={active}/><div className="content-wrap">{content}</div></main>{selectedTrip && <div/>}</div> }

function ItineraryPage() { const [stops, setStops] = useState([{ city: "Kyoto", country: "Japan", days: "Apr 12 – 16", activities: ["Fushimi Inari Shrine", "Nishiki Market"] }, { city: "Osaka", country: "Japan", days: "Apr 16 – 19", activities: ["Dotonbori food walk"] }]); const [newStop, setNewStop] = useState(""); return <><div className="page-intro"><div><p className="eyebrow accent-text">Japan Adventure · 8 days</p><h2>Build your itinerary</h2><p>Shape the journey one thoughtful stop at a time.</p></div><Button className="primary-button" onClick={() => toast.success("Itinerary shared with your travel circle.")}><Share2 size={17}/> Share itinerary</Button></div><ActivitySearch/><div className="itinerary-layout"><div className="itinerary-main">{stops.map((stop, i) => <article className="stop-card" key={stop.city}><div className="stop-number">0{i+1}</div><div className="stop-content"><div className="stop-heading"><div><p className="eyebrow">Stop {i+1}</p><h3>{stop.city}</h3><span>{stop.country} · {stop.days}</span></div><button className="icon-button" onClick={() => setStops(stops.filter(s => s.city !== stop.city))}><Trash2 size={15}/></button></div><div className="activity-list">{stop.activities.map(activity => <div className="activity-row" key={activity}><CheckCircle2 size={15}/><span>{activity}</span><small>View details</small></div>)}</div><button className="add-activity" onClick={() => toast.success("Activity search opened for this city.")}><Plus size={15}/> Add activity</button></div></article>)}<div className="add-stop-row"><Input placeholder="Add a city, e.g. Tokyo" value={newStop} onChange={e=>setNewStop(e.target.value)} /><Button variant="outline" onClick={() => { if (newStop.trim()) { setStops([...stops, { city: newStop, country: "New destination", days: "Dates to set", activities: [] }]); setNewStop(""); toast.success("Stop added to your itinerary."); } }}><Plus size={16}/> Add stop</Button></div></div><div className="budget-card panel"><p className="eyebrow">Trip budget</p><h3>$1,240 <span>/ $2,600</span></h3><div className="progress-track"><i style={{width:"48%"}}/></div><div className="budget-line"><span>Spent so far</span><b>48%</b></div><div className="budget-breakdown"><span><i className="dot teal-dot"/>Stay <b>$620</b></span><span><i className="dot blue-dot"/>Activities <b>$385</b></span><span><i className="dot gold-dot"/>Meals <b>$235</b></span></div><Button variant="outline" onClick={() => toast.info("Budget editor opened.")}>View cost breakdown <ArrowRight size={14}/></Button></div></div></> }

function ActivitySearch() { const [query, setQuery] = useState(""); const [category, setCategory] = useState("all"); const [maxCost, setMaxCost] = useState("any"); const [duration, setDuration] = useState("any"); const places = trpc.travel.places.useQuery({ lat: 35.0116, lon: 135.7681, query: query || undefined }, { enabled: query.trim().length > 2 }); const fallback = [{ name: "Fushimi Inari Shrine", category: "culture", cost: 0, duration: "2h" }, { name: "Nishiki Market", category: "food", cost: 20, duration: "2h" }, { name: "Arashiyama Bamboo Grove", category: "nature", cost: 12, duration: "3h" }]; const items = (places.data?.length ? places.data : fallback).filter((item: any) => category === "all" || String(item.category || "").toLowerCase().includes(category)).filter((item: any) => maxCost === "any" || Number(item.cost || 0) <= Number(maxCost)).filter((item: any) => duration === "any" || (duration === "short" ? Number.parseFloat(String(item.duration || "3").replace(/[^0-9.]/g, "")) <= 2 : Number.parseFloat(String(item.duration || "3").replace(/[^0-9.]/g, "")) > 2)); return <div className="activity-search panel"><div className="panel-heading"><div><p className="eyebrow">Discover things to do</p><h3>Activity search</h3></div><Badge>{items.length} options</Badge></div><div className="activity-filters"><Input placeholder="Search activities" value={query} onChange={e=>setQuery(e.target.value)} /><select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All categories</option><option value="culture">Culture</option><option value="food">Food</option><option value="nature">Nature</option></select><select value={maxCost} onChange={e=>setMaxCost(e.target.value)}><option value="any">Any cost</option><option value="0">Free</option><option value="25">Under $25</option><option value="100">Under $100</option></select><select value={duration} onChange={e=>setDuration(e.target.value)}><option value="any">Any duration</option><option value="short">Under 2 hours</option><option value="long">Half day</option></select></div><div className="activity-results">{items.map((item: any, i: number) => <div className="activity-result" key={item.id || item.name || i}><div><b>{item.name}</b><span>{item.category || "Experience"} · {item.duration || "Flexible timing"} · {Number(item.cost || 0) ? `$${item.cost}` : "Free"}</span></div><Button variant="outline" onClick={() => toast.success(`${item.name} added to your itinerary.`)}><Plus size={15}/> Add</Button></div>)}</div></div> }

function CommunityLive() { const [posts, setPosts] = useState<any[]>([]); const [text, setText] = useState(""); useEffect(() => { if (!supabase) return; listCommunityPosts().then(setPosts).catch(() => setPosts([])); }, []); const publish = async () => { if (!text.trim()) return; try { if (supabase) { const post = await createCommunityPost(text.trim()); setPosts([post, ...posts]); } else setPosts([{ id: Date.now(), content: text.trim(), created_at: new Date().toISOString() }, ...posts]); setText(""); toast.success("Post shared with the community."); } catch (error: any) { toast.error(error.message || "Could not publish post."); } }; return <><div className="page-intro"><div><p className="eyebrow accent-text">Travel together</p><h2>Community</h2><p>Get inspired by people who never stop exploring.</p></div></div><div className="community-layout"><div className="post-composer"><div className="avatar">AM</div><div><Textarea placeholder="Share a travel thought, tip, or story..." value={text} onChange={e => setText(e.target.value)} /><div className="composer-actions"><button><ImagePlus size={16}/> Add photo</button><Button className="primary-button" onClick={publish}>Share post</Button></div></div></div><div className="post-list">{posts.length ? posts.map((p, i) => <article className="community-post" key={p.id || i}><div className="post-author"><div className="avatar small">AM</div><div><b>GlobeTrotter traveler</b><span>{p.created_at ? new Date(p.created_at).toLocaleDateString() : "Just now"}</span></div><MoreHorizontal size={17}/></div><p>{p.content}</p><div className="post-actions"><button><Heart size={16}/> Like</button><button><Share2 size={16}/> Share</button></div></article>) : <div className="panel empty-state"><Users size={22}/><h3>Be the first to share</h3><p>Your travel notes will appear here for the community.</p></div>}</div></div></> }

function ExploreLive({ setActive, trips, setTrips }: any) { const [query, setQuery] = useState(""); const [country, setCountry] = useState("all"); const cityQuery = trpc.travel.cities.useQuery({ query }, { enabled: query.trim().length > 2 }); const imageQuery = trpc.travel.images.useQuery({ query }, { enabled: query.trim().length > 2 }); const cities = (cityQuery.data?.length ? cityQuery.data : destinations.map((d, i) => ({ id: i, city: d.city, country: d.country }))).filter((d: any) => country === "all" || d.country === country); return <><div className="page-intro"><div><p className="eyebrow accent-text">Wander further</p><h2>Explore destinations</h2><p>Search live city data and discover places worth building a trip around.</p></div></div><div className="explore-search"><Search size={18}/><input placeholder="Search city, country, or experience" value={query} onChange={e => setQuery(e.target.value)} /><Button className="primary-button" onClick={() => toast.success("Searching destinations…")}>Search</Button><select className="explore-filter" value={country} onChange={e => setCountry(e.target.value)}><option value="all">All countries</option><option value="Portugal">Portugal</option><option value="Japan">Japan</option><option value="Norway">Norway</option></select></div><div className="destination-large-grid">{cities.slice(0, 6).map((d: any, i: number) => <article className="explore-card" key={d.id || d.city}><img src={imageQuery.data?.[i]?.url || destinations[i % destinations.length].image} /><div className="explore-card-body"><div><p className="eyebrow">{d.region || "Destination"}</p><h3>{d.city}</h3><span>{d.country}</span></div><button className="heart-button"><Heart size={17}/></button><Button variant="outline" onClick={async () => { try { const target = trips?.[0]; if (supabase && target && typeof target.id === "string") await addStop({ trip_id: target.id, city_name: d.city, country: d.country, order_index: target.stops || 0 }); if (target) setTrips(trips.map((t: any) => t.id === target.id ? { ...t, stops: (t.stops || 0) + 1 } : t)); toast.success(`${d.city} added to ${target?.name || "your itinerary"}.`); setActive("itinerary"); } catch (error: any) { toast.error(error.message || "Could not add this destination."); } }}>Add to trip <Plus size={15}/></Button></div></article>)}</div></> }

function SettingsPage() { const [firstName, setFirstName] = useState("Alex"); const [lastName, setLastName] = useState("Morgan"); const [email, setEmail] = useState("alex@example.com"); const [city, setCity] = useState("New York"); const [bio, setBio] = useState("Always planning the next adventure."); const [avatarUrl, setAvatarUrl] = useState(""); const save = async () => { try { if (supabase) { const user = await currentUserId(); if (user) { const { error } = await supabase.from("profiles").upsert({ id: user, first_name: firstName, last_name: lastName, city, additional_info: bio, avatar_url: avatarUrl || null }); if (error) throw error; } } toast.success("Profile saved."); } catch (error: any) { toast.error(error.message || "Could not save profile."); } }; const onAvatar = async (file?: File) => { if (!file) return; try { const url = await uploadAvatar(file); setAvatarUrl(url); toast.success("Avatar uploaded. Save your profile to keep it."); } catch (error: any) { toast.error(error.message || "Could not upload avatar."); } }; return <><div className="page-intro"><div><p className="eyebrow accent-text">Your account</p><h2>Profile & settings</h2><p>Make GlobeTrotter feel like your own travel journal.</p></div></div><div className="settings-panel"><div className="settings-avatar">{avatarUrl ? <img className="avatar large avatar-image" src={avatarUrl} /> : <div className="avatar large">AM</div>}<label className="upload-button">Change photo<input type="file" accept="image/*" onChange={e=>onAvatar(e.target.files?.[0])}/></label></div><div className="settings-fields"><label>First name<Input value={firstName} onChange={e=>setFirstName(e.target.value)} /></label><label>Last name<Input value={lastName} onChange={e=>setLastName(e.target.value)} /></label><label>Email address<Input value={email} onChange={e=>setEmail(e.target.value)} type="email" /></label><label>Home city<Input value={city} onChange={e=>setCity(e.target.value)} /></label><label className="wide">Travel bio<Textarea value={bio} onChange={e=>setBio(e.target.value)} /></label><label>Language<select defaultValue="English"><option>English</option><option>Spanish</option><option>Japanese</option></select></label><Button className="primary-button" onClick={save}>Save changes</Button><button className="danger-button" onClick={async () => { if (!window.confirm("Delete your GlobeTrotter data? This cannot be undone.")) return; try { await deleteAccountData(); toast.success("Your data was deleted."); window.location.href = "/login"; } catch (error: any) { toast.error(error.message || "Could not delete your data."); } }}>Delete my account data</button></div></div></> }
